// src/feature-generator/frontend/react/shared-controls.generator.js
import { getFrontendFilePath } from '../../../utils/project-paths.js';
import { frontendSourceName } from '../emit-language.js';

/**
 * Plan the shared, reusable React form controls used by generated feature
 * modules. Every file is written only when it does not already exist so that
 * user customizations survive regeneration.
 *
 * @param {object} [config]
 * @returns {{ relativePath: string, contents: string, writeMode: 'ifMissing' }[]}
 */
export function planSharedReactControls(config = {}) {
  const src = (name) => frontendSourceName(config, name);
  const formsBase = (...segments) =>
    getFrontendFilePath(config, 'src', 'shared', 'components', 'forms', ...segments);
  const typesBase = (...segments) =>
    getFrontendFilePath(config, 'src', 'shared', 'types', ...segments);

  return [
    {
      relativePath: typesBase(src('stored-file.types.ts')),
      contents: STORED_FILE_TYPES,
      writeMode: 'ifMissing',
    },
    {
      relativePath: typesBase(src('lookup.types.ts')),
      contents: LOOKUP_TYPES,
      writeMode: 'ifMissing',
    },
    {
      relativePath: formsBase(src('EnumSelect.tsx')),
      contents: ENUM_SELECT,
      writeMode: 'ifMissing',
    },
    {
      relativePath: formsBase(src('LookupSelect.tsx')),
      contents: LOOKUP_SELECT,
      writeMode: 'ifMissing',
    },
    {
      relativePath: formsBase(src('MultiLookupSelect.tsx')),
      contents: MULTI_LOOKUP_SELECT,
      writeMode: 'ifMissing',
    },
    {
      relativePath: formsBase(src('FileUploadField.tsx')),
      contents: FILE_UPLOAD_FIELD,
      writeMode: 'ifMissing',
    },
    {
      relativePath: formsBase(src('ImageUploadField.tsx')),
      contents: IMAGE_UPLOAD_FIELD,
      writeMode: 'ifMissing',
    },
  ];
}

const STORED_FILE_TYPES = `export type StoredFileDto = {
  id: string;
  fileName: string;
  contentType: string;
  sizeBytes: number;
  url: string;
};
`;

const LOOKUP_TYPES = `export type LookupOption = {
  id: string;
  displayName: string;
};
`;

const ENUM_SELECT = `"use client";

type EnumSelectOption = {
  value: number;
  label: string;
};

type EnumSelectProps = {
  value: number | null;
  onChange: (value: number) => void;
  options: readonly EnumSelectOption[];
  placeholder?: string;
  id?: string;
  disabled?: boolean;
};

export function EnumSelect({
  value,
  onChange,
  options,
  placeholder = "Select...",
  id,
  disabled,
}: EnumSelectProps) {
  return (
    <select
      id={id}
      disabled={disabled}
      value={value ?? ""}
      onChange={(event) => onChange(Number(event.target.value))}
      className="rounded-md border border-zinc-300 bg-white px-3 py-2 text-sm text-zinc-900"
    >
      <option value="" disabled>
        {placeholder}
      </option>
      {options.map((option) => (
        <option key={option.value} value={option.value}>
          {option.label}
        </option>
      ))}
    </select>
  );
}
`;

const LOOKUP_SELECT = `"use client";

import { useEffect, useState } from "react";
import { apiClient } from "@/lib/api/api-client";
import { getErrorMessage } from "@/shared/utils/get-error-message";
import type { LookupOption } from "@/shared/types/lookup.types";

type LookupSelectProps = {
  value: string | null;
  onChange: (value: string | null) => void;
  endpoint: string;
  placeholder?: string;
  id?: string;
  disabled?: boolean;
};

export function LookupSelect({
  value,
  onChange,
  endpoint,
  placeholder = "Select...",
  id,
  disabled,
}: LookupSelectProps) {
  const [options, setOptions] = useState<LookupOption[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);

  useEffect(() => {
    let active = true;
    setIsLoading(true);
    apiClient
      .get<LookupOption[]>(endpoint)
      .then((response) => {
        if (active) {
          setOptions(response.data);
          setError(null);
        }
      })
      .catch((cause) => {
        if (active) {
          setError(getErrorMessage(cause));
        }
      })
      .finally(() => {
        if (active) {
          setIsLoading(false);
        }
      });

    return () => {
      active = false;
    };
  }, [endpoint]);

  return (
    <div className="flex flex-col gap-1">
      <select
        id={id}
        disabled={disabled || isLoading}
        value={value ?? ""}
        onChange={(event) =>
          onChange(event.target.value ? event.target.value : null)
        }
        className="rounded-md border border-zinc-300 bg-white px-3 py-2 text-sm text-zinc-900"
      >
        <option value="">{isLoading ? "Loading..." : placeholder}</option>
        {options.map((option) => (
          <option key={option.id} value={option.id}>
            {option.displayName}
          </option>
        ))}
      </select>
      {error ? (
        <p className="text-xs text-red-600" role="alert">
          {error}
        </p>
      ) : null}
    </div>
  );
}
`;

const MULTI_LOOKUP_SELECT = `"use client";

import { useEffect, useState } from "react";
import { apiClient } from "@/lib/api/api-client";
import { getErrorMessage } from "@/shared/utils/get-error-message";
import type { LookupOption } from "@/shared/types/lookup.types";

type MultiLookupSelectProps = {
  value: string[];
  onChange: (value: string[]) => void;
  endpoint: string;
  disabled?: boolean;
};

export function MultiLookupSelect({
  value,
  onChange,
  endpoint,
  disabled,
}: MultiLookupSelectProps) {
  const [options, setOptions] = useState<LookupOption[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);

  useEffect(() => {
    let active = true;
    setIsLoading(true);
    apiClient
      .get<LookupOption[]>(endpoint)
      .then((response) => {
        if (active) {
          setOptions(response.data);
          setError(null);
        }
      })
      .catch((cause) => {
        if (active) {
          setError(getErrorMessage(cause));
        }
      })
      .finally(() => {
        if (active) {
          setIsLoading(false);
        }
      });

    return () => {
      active = false;
    };
  }, [endpoint]);

  const toggle = (id: string) => {
    if (value.includes(id)) {
      onChange(value.filter((item) => item !== id));
    } else {
      onChange([...value, id]);
    }
  };

  return (
    <div className="flex flex-col gap-2">
      {isLoading ? <p className="text-xs text-zinc-500">Loading...</p> : null}
      <div className="flex flex-wrap gap-2">
        {options.map((option) => {
          const checked = value.includes(option.id);
          return (
            <label
              key={option.id}
              className={
                checked
                  ? "flex cursor-pointer items-center gap-2 rounded-md border border-zinc-900 bg-zinc-900 px-3 py-1.5 text-sm text-white"
                  : "flex cursor-pointer items-center gap-2 rounded-md border border-zinc-300 bg-white px-3 py-1.5 text-sm text-zinc-800"
              }
            >
              <input
                type="checkbox"
                className="sr-only"
                checked={checked}
                disabled={disabled}
                onChange={() => toggle(option.id)}
              />
              {option.displayName}
            </label>
          );
        })}
      </div>
      {error ? (
        <p className="text-xs text-red-600" role="alert">
          {error}
        </p>
      ) : null}
    </div>
  );
}
`;

const FILE_UPLOAD_FIELD = `"use client";

import { useState } from "react";
import { apiClient } from "@/lib/api/api-client";
import { getErrorMessage } from "@/shared/utils/get-error-message";
import type { StoredFileDto } from "@/shared/types/stored-file.types";

type BaseUploadProps = {
  accept?: string;
  maxFiles?: number;
  maxSizeBytes?: number;
  disabled?: boolean;
};

type SingleFileProps = BaseUploadProps & {
  multiple?: false;
  value: string | null;
  onChange: (value: string | null) => void;
};

type MultiFileProps = BaseUploadProps & {
  multiple: true;
  value: string[];
  onChange: (value: string[]) => void;
};

type FileUploadFieldProps = SingleFileProps | MultiFileProps;

async function uploadFile(file: File): Promise<StoredFileDto> {
  const formData = new FormData();
  formData.append("file", file);
  const response = await apiClient.post<StoredFileDto>("/api/v1/Files", formData);
  return response.data;
}

export function FileUploadField(props: FileUploadFieldProps) {
  const { accept, maxFiles, maxSizeBytes, disabled } = props;
  const [files, setFiles] = useState<StoredFileDto[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [isUploading, setIsUploading] = useState(false);

  const emit = (next: StoredFileDto[]) => {
    if (props.multiple) {
      props.onChange(next.map((item) => item.id));
    } else {
      props.onChange(next.length > 0 ? next[0].id : null);
    }
  };

  const handleSelect = async (selected: FileList | null) => {
    if (!selected || selected.length === 0) {
      return;
    }

    setError(null);
    setIsUploading(true);
    try {
      const incoming = Array.from(selected);
      for (const file of incoming) {
        if (maxSizeBytes && file.size > maxSizeBytes) {
          throw new Error(file.name + " exceeds the maximum file size.");
        }
      }

      const uploaded: StoredFileDto[] = [];
      for (const file of incoming) {
        uploaded.push(await uploadFile(file));
      }

      if (props.multiple) {
        const merged = [...files, ...uploaded];
        const next =
          typeof maxFiles === "number" ? merged.slice(0, maxFiles) : merged;
        setFiles(next);
        emit(next);
      } else {
        const next = uploaded.slice(0, 1);
        setFiles(next);
        emit(next);
      }
    } catch (cause) {
      setError(getErrorMessage(cause));
    } finally {
      setIsUploading(false);
    }
  };

  const removeFile = (id: string) => {
    const next = files.filter((item) => item.id !== id);
    setFiles(next);
    emit(next);
  };

  return (
    <div className="flex flex-col gap-2">
      <input
        type="file"
        accept={accept}
        multiple={props.multiple}
        disabled={disabled || isUploading}
        onChange={(event) => {
          void handleSelect(event.target.files);
        }}
        className="block text-sm text-zinc-700 file:mr-3 file:rounded-md file:border-0 file:bg-zinc-900 file:px-3 file:py-1.5 file:text-sm file:text-white"
      />
      {isUploading ? (
        <p className="text-xs text-zinc-500">Uploading...</p>
      ) : null}
      {files.length > 0 ? (
        <ul className="flex flex-col gap-1">
          {files.map((file) => (
            <li
              key={file.id}
              className="flex items-center justify-between rounded-md border border-zinc-200 px-3 py-1.5 text-sm text-zinc-800"
            >
              <span className="truncate">{file.fileName}</span>
              <button
                type="button"
                className="text-xs text-red-600 underline"
                onClick={() => removeFile(file.id)}
              >
                Remove
              </button>
            </li>
          ))}
        </ul>
      ) : null}
      {error ? (
        <p className="text-xs text-red-600" role="alert">
          {error}
        </p>
      ) : null}
    </div>
  );
}
`;

const IMAGE_UPLOAD_FIELD = `"use client";

import { useState } from "react";
import { apiClient } from "@/lib/api/api-client";
import { getErrorMessage } from "@/shared/utils/get-error-message";
import type { StoredFileDto } from "@/shared/types/stored-file.types";

type BaseUploadProps = {
  accept?: string;
  maxFiles?: number;
  maxSizeBytes?: number;
  disabled?: boolean;
};

type SingleImageProps = BaseUploadProps & {
  multiple?: false;
  value: string | null;
  onChange: (value: string | null) => void;
};

type MultiImageProps = BaseUploadProps & {
  multiple: true;
  value: string[];
  onChange: (value: string[]) => void;
};

type ImageUploadFieldProps = SingleImageProps | MultiImageProps;

async function uploadFile(file: File): Promise<StoredFileDto> {
  const formData = new FormData();
  formData.append("file", file);
  const response = await apiClient.post<StoredFileDto>("/api/v1/Files", formData);
  return response.data;
}

export function ImageUploadField(props: ImageUploadFieldProps) {
  const { accept = "image/*", maxFiles, maxSizeBytes, disabled } = props;
  const [files, setFiles] = useState<StoredFileDto[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [isUploading, setIsUploading] = useState(false);

  const emit = (next: StoredFileDto[]) => {
    if (props.multiple) {
      props.onChange(next.map((item) => item.id));
    } else {
      props.onChange(next.length > 0 ? next[0].id : null);
    }
  };

  const handleSelect = async (selected: FileList | null) => {
    if (!selected || selected.length === 0) {
      return;
    }

    setError(null);
    setIsUploading(true);
    try {
      const incoming = Array.from(selected);
      for (const file of incoming) {
        if (maxSizeBytes && file.size > maxSizeBytes) {
          throw new Error(file.name + " exceeds the maximum file size.");
        }
      }

      const uploaded: StoredFileDto[] = [];
      for (const file of incoming) {
        uploaded.push(await uploadFile(file));
      }

      if (props.multiple) {
        const merged = [...files, ...uploaded];
        const next =
          typeof maxFiles === "number" ? merged.slice(0, maxFiles) : merged;
        setFiles(next);
        emit(next);
      } else {
        const next = uploaded.slice(0, 1);
        setFiles(next);
        emit(next);
      }
    } catch (cause) {
      setError(getErrorMessage(cause));
    } finally {
      setIsUploading(false);
    }
  };

  const removeFile = (id: string) => {
    const next = files.filter((item) => item.id !== id);
    setFiles(next);
    emit(next);
  };

  return (
    <div className="flex flex-col gap-2">
      <input
        type="file"
        accept={accept}
        multiple={props.multiple}
        disabled={disabled || isUploading}
        onChange={(event) => {
          void handleSelect(event.target.files);
        }}
        className="block text-sm text-zinc-700 file:mr-3 file:rounded-md file:border-0 file:bg-zinc-900 file:px-3 file:py-1.5 file:text-sm file:text-white"
      />
      {isUploading ? (
        <p className="text-xs text-zinc-500">Uploading...</p>
      ) : null}
      {files.length > 0 ? (
        <div className="flex flex-wrap gap-3">
          {files.map((file) => (
            <div key={file.id} className="flex flex-col items-center gap-1">
              <img
                src={file.url}
                alt={file.fileName}
                className="h-20 w-20 rounded-md border border-zinc-200 object-cover"
              />
              <button
                type="button"
                className="text-xs text-red-600 underline"
                onClick={() => removeFile(file.id)}
              >
                Remove
              </button>
            </div>
          ))}
        </div>
      ) : null}
      {error ? (
        <p className="text-xs text-red-600" role="alert">
          {error}
        </p>
      ) : null}
    </div>
  );
}
`;

// src/feature-generator/frontend/angular/shared-controls.generator.js
import { getFrontendFilePath } from '../../../utils/project-paths.js';

/**
 * Plan the shared Angular form controls and support models used by generated
 * features (relationship lookups, enum selects, and media uploads).
 *
 * Every entry uses `writeMode: 'ifMissing'` so re-running the feature generator
 * never clobbers a shared control the user may have customised.
 *
 * @param {object} [config]
 * @returns {{ relativePath: string, contents: string, writeMode: 'ifMissing' }[]}
 */
export function planSharedAngularControls(config = {}) {
  const formsDir = (...segments) =>
    getFrontendFilePath(config, 'src', 'app', 'shared', 'components', 'forms', ...segments);
  const modelsDir = (...segments) =>
    getFrontendFilePath(config, 'src', 'app', 'shared', 'models', ...segments);

  return [
    {
      relativePath: modelsDir('lookup.model.ts'),
      contents: renderLookupModel(),
      writeMode: 'ifMissing',
    },
    {
      relativePath: modelsDir('stored-file.model.ts'),
      contents: renderStoredFileModel(),
      writeMode: 'ifMissing',
    },
    {
      relativePath: formsDir('lookup-select.component.ts'),
      contents: renderLookupSelect(),
      writeMode: 'ifMissing',
    },
    {
      relativePath: formsDir('multi-lookup-select.component.ts'),
      contents: renderMultiLookupSelect(),
      writeMode: 'ifMissing',
    },
    {
      relativePath: formsDir('enum-select.component.ts'),
      contents: renderEnumSelect(),
      writeMode: 'ifMissing',
    },
    {
      relativePath: formsDir('file-upload-field.component.ts'),
      contents: renderFileUploadField(),
      writeMode: 'ifMissing',
    },
    {
      relativePath: formsDir('image-upload-field.component.ts'),
      contents: renderImageUploadField(),
      writeMode: 'ifMissing',
    },
  ];
}

function renderLookupModel() {
  return `export type LookupOption = {
  value: string;
  label: string;
};
`;
}

function renderStoredFileModel() {
  return `export type StoredFile = {
  id: string;
  fileName: string;
  url: string;
  contentType: string;
  size: number;
};
`;
}

function renderLookupSelect() {
  return `import { Component, forwardRef, input, signal } from "@angular/core";
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from "@angular/forms";
import type { LookupOption } from "../../models/lookup.model";

@Component({
  selector: "app-lookup-select",
  standalone: true,
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => LookupSelectComponent),
      multi: true,
    },
  ],
  template: \`
    <select
      class="w-full rounded-md border border-zinc-300 bg-white px-3 py-2 text-sm text-zinc-900 disabled:opacity-60"
      [value]="value() ?? ''"
      [disabled]="disabled()"
      (change)="handleChange($any($event.target).value)"
      (blur)="handleBlur()"
    >
      <option value="">{{ placeholder() }}</option>
      @for (option of options(); track option.value) {
        <option [value]="option.value">{{ option.label }}</option>
      }
    </select>
  \`,
})
export class LookupSelectComponent implements ControlValueAccessor {
  readonly options = input<LookupOption[]>([]);
  readonly placeholder = input<string>("Select...");

  protected readonly value = signal<string | null>(null);
  protected readonly disabled = signal(false);

  private onChange: (value: string | null) => void = () => {};
  private onTouched: () => void = () => {};

  writeValue(value: string | null): void {
    this.value.set(value ?? null);
  }

  registerOnChange(fn: (value: string | null) => void): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onTouched = fn;
  }

  setDisabledState(isDisabled: boolean): void {
    this.disabled.set(isDisabled);
  }

  protected handleChange(raw: string): void {
    const next = raw ? raw : null;
    this.value.set(next);
    this.onChange(next);
    this.onTouched();
  }

  protected handleBlur(): void {
    this.onTouched();
  }
}
`;
}

function renderMultiLookupSelect() {
  return `import { Component, forwardRef, input, signal } from "@angular/core";
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from "@angular/forms";
import type { LookupOption } from "../../models/lookup.model";

@Component({
  selector: "app-multi-lookup-select",
  standalone: true,
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => MultiLookupSelectComponent),
      multi: true,
    },
  ],
  template: \`
    <div class="flex flex-col gap-2 rounded-md border border-zinc-300 bg-white p-3">
      @if (options().length === 0) {
        <p class="text-sm text-zinc-500">No options available.</p>
      }
      @for (option of options(); track option.value) {
        <label class="flex items-center gap-2 text-sm text-zinc-800">
          <input
            type="checkbox"
            class="h-4 w-4 rounded border-zinc-300"
            [checked]="isSelected(option.value)"
            [disabled]="disabled()"
            (change)="toggle(option.value, $any($event.target).checked)"
          />
          {{ option.label }}
        </label>
      }
    </div>
  \`,
})
export class MultiLookupSelectComponent implements ControlValueAccessor {
  readonly options = input<LookupOption[]>([]);

  protected readonly selected = signal<string[]>([]);
  protected readonly disabled = signal(false);

  private onChange: (value: string[]) => void = () => {};
  private onTouched: () => void = () => {};

  writeValue(value: string[] | null): void {
    this.selected.set(value ?? []);
  }

  registerOnChange(fn: (value: string[]) => void): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onTouched = fn;
  }

  setDisabledState(isDisabled: boolean): void {
    this.disabled.set(isDisabled);
  }

  protected isSelected(value: string): boolean {
    return this.selected().includes(value);
  }

  protected toggle(value: string, checked: boolean): void {
    const set = new Set(this.selected());
    if (checked) {
      set.add(value);
    } else {
      set.delete(value);
    }
    const next = Array.from(set);
    this.selected.set(next);
    this.onChange(next);
    this.onTouched();
  }
}
`;
}

function renderEnumSelect() {
  return `import { Component, forwardRef, input, signal } from "@angular/core";
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from "@angular/forms";
import type { LookupOption } from "../../models/lookup.model";

@Component({
  selector: "app-enum-select",
  standalone: true,
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => EnumSelectComponent),
      multi: true,
    },
  ],
  template: \`
    <select
      class="w-full rounded-md border border-zinc-300 bg-white px-3 py-2 text-sm text-zinc-900 disabled:opacity-60"
      [value]="value() ?? ''"
      [disabled]="disabled()"
      (change)="handleChange($any($event.target).value)"
      (blur)="handleBlur()"
    >
      <option value="">{{ placeholder() }}</option>
      @for (option of options(); track option.value) {
        <option [value]="option.value">{{ option.label }}</option>
      }
    </select>
  \`,
})
export class EnumSelectComponent implements ControlValueAccessor {
  readonly options = input<LookupOption[]>([]);
  readonly placeholder = input<string>("Select...");

  protected readonly value = signal<string | null>(null);
  protected readonly disabled = signal(false);

  private onChange: (value: string | null) => void = () => {};
  private onTouched: () => void = () => {};

  writeValue(value: string | null): void {
    this.value.set(value ?? null);
  }

  registerOnChange(fn: (value: string | null) => void): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onTouched = fn;
  }

  setDisabledState(isDisabled: boolean): void {
    this.disabled.set(isDisabled);
  }

  protected handleChange(raw: string): void {
    const next = raw ? raw : null;
    this.value.set(next);
    this.onChange(next);
    this.onTouched();
  }

  protected handleBlur(): void {
    this.onTouched();
  }
}
`;
}

function renderFileUploadField() {
  return `import { HttpClient } from "@angular/common/http";
import { Component, forwardRef, inject, input, signal } from "@angular/core";
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from "@angular/forms";
import type { StoredFile } from "../../models/stored-file.model";

const FILES_ENDPOINT = "/api/v1/Files";

@Component({
  selector: "app-file-upload-field",
  standalone: true,
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => FileUploadFieldComponent),
      multi: true,
    },
  ],
  template: \`
    <div class="flex flex-col gap-2">
      <input
        type="file"
        class="block w-full text-sm text-zinc-700 file:mr-3 file:rounded-md file:border-0 file:bg-zinc-900 file:px-3 file:py-2 file:text-sm file:text-white"
        [accept]="accept()"
        [disabled]="disabled() || uploading()"
        (change)="onFileSelected($event)"
        (blur)="handleBlur()"
      />
      @if (uploading()) {
        <p class="text-sm text-zinc-500">Uploading...</p>
      } @else if (fileName(); as name) {
        <p class="text-sm text-zinc-600">Uploaded: {{ name }}</p>
      }
    </div>
  \`,
})
export class FileUploadFieldComponent implements ControlValueAccessor {
  readonly accept = input<string>("*/*");

  private readonly http = inject(HttpClient);

  protected readonly value = signal<string | null>(null);
  protected readonly fileName = signal<string | null>(null);
  protected readonly uploading = signal(false);
  protected readonly disabled = signal(false);

  private onChange: (value: string | null) => void = () => {};
  private onTouched: () => void = () => {};

  writeValue(value: string | null): void {
    this.value.set(value ?? null);
  }

  registerOnChange(fn: (value: string | null) => void): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onTouched = fn;
  }

  setDisabledState(isDisabled: boolean): void {
    this.disabled.set(isDisabled);
  }

  protected handleBlur(): void {
    this.onTouched();
  }

  protected onFileSelected(event: Event): void {
    const target = event.target as HTMLInputElement;
    const file = target.files?.[0];
    if (!file) {
      return;
    }

    const formData = new FormData();
    formData.append("file", file);
    this.uploading.set(true);

    this.http.post<StoredFile>(FILES_ENDPOINT, formData).subscribe({
      next: (stored) => {
        this.value.set(stored.id);
        this.fileName.set(stored.fileName);
        this.uploading.set(false);
        this.onChange(stored.id);
        this.onTouched();
      },
      error: () => {
        this.uploading.set(false);
      },
    });
  }
}
`;
}

function renderImageUploadField() {
  return `import { HttpClient } from "@angular/common/http";
import { Component, forwardRef, inject, input, signal } from "@angular/core";
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from "@angular/forms";
import type { StoredFile } from "../../models/stored-file.model";

const FILES_ENDPOINT = "/api/v1/Files";

@Component({
  selector: "app-image-upload-field",
  standalone: true,
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => ImageUploadFieldComponent),
      multi: true,
    },
  ],
  template: \`
    <div class="flex flex-col gap-3">
      @if (previewUrl(); as url) {
        <img
          [src]="url"
          alt="Preview"
          class="h-32 w-32 rounded-md border border-zinc-200 object-cover"
        />
      }
      <input
        type="file"
        accept="image/*"
        class="block w-full text-sm text-zinc-700 file:mr-3 file:rounded-md file:border-0 file:bg-zinc-900 file:px-3 file:py-2 file:text-sm file:text-white"
        [disabled]="disabled() || uploading()"
        (change)="onFileSelected($event)"
        (blur)="handleBlur()"
      />
      @if (uploading()) {
        <p class="text-sm text-zinc-500">Uploading...</p>
      }
    </div>
  \`,
})
export class ImageUploadFieldComponent implements ControlValueAccessor {
  private readonly http = inject(HttpClient);

  protected readonly value = signal<string | null>(null);
  protected readonly previewUrl = signal<string | null>(null);
  protected readonly uploading = signal(false);
  protected readonly disabled = signal(false);

  private onChange: (value: string | null) => void = () => {};
  private onTouched: () => void = () => {};

  writeValue(value: string | null): void {
    this.value.set(value ?? null);
  }

  registerOnChange(fn: (value: string | null) => void): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onTouched = fn;
  }

  setDisabledState(isDisabled: boolean): void {
    this.disabled.set(isDisabled);
  }

  protected handleBlur(): void {
    this.onTouched();
  }

  protected onFileSelected(event: Event): void {
    const target = event.target as HTMLInputElement;
    const file = target.files?.[0];
    if (!file) {
      return;
    }

    const formData = new FormData();
    formData.append("file", file);
    this.uploading.set(true);

    this.http.post<StoredFile>(FILES_ENDPOINT, formData).subscribe({
      next: (stored) => {
        this.value.set(stored.id);
        this.previewUrl.set(stored.url);
        this.uploading.set(false);
        this.onChange(stored.id);
        this.onTouched();
      },
      error: () => {
        this.uploading.set(false);
      },
    });
  }
}
`;
}
