// src/templates/frontend/react/common/src/modules/example/pages/ExamplesPage.tsx
"use client";

import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { ExampleCard } from "../components/ExampleCard";
import { useExamplesController } from "../hooks/useExamplesController";
import {
  createExampleSchema,
  type CreateExampleFormValues,
} from "../schemas/example.schema";
import { PageHeader } from "@/shared/components/common/PageHeader";
import { EmptyState } from "@/shared/components/empty-state/EmptyState";
import { ErrorState } from "@/shared/components/empty-state/ErrorState";
import { LoadingState } from "@/shared/components/loaders/LoadingState";

export default function ExamplesPage() {
  const { items, status, error, load, create } = useExamplesController();
  const form = useForm<CreateExampleFormValues>({
    resolver: zodResolver(createExampleSchema),
    defaultValues: {
      name: "",
      description: "",
    },
  });

  return (
    <main className="ui-container ui-page" style={{ paddingTop: "2.5rem", paddingBottom: "3.5rem" }}>
      <PageHeader
        title="Architecture sample"
        description="Page → controller → service → API client. This slice exists so the generated client has a working module before you add domain features."
        actions={
          <button type="button" className="ui-btn ui-btn-ghost" onClick={() => load({ page: 1, pageSize: 10 })}>
            Load sample
          </button>
        }
      />

      {status === "failed" && error ? <ErrorState description={error} /> : null}
      {status === "loading" ? <LoadingState description="Calling the sample endpoint…" /> : null}

      <form
        className="ui-card"
        style={{ margin: "1.2rem 0" }}
        onSubmit={form.handleSubmit((values) => create(values))}
      >
        <h3>Create a sample record</h3>
        <label className="ui-field">
          Name
          <input className="ui-input" {...form.register("name")} />
        </label>
        <label className="ui-field">
          Description
          <textarea className="ui-input" rows={3} {...form.register("description")} />
        </label>
        <button type="submit" className="ui-btn ui-btn-primary">
          Save
        </button>
      </form>

      {items.length === 0 && status !== "loading" ? (
        <EmptyState
          title="No sample records"
          description="The sample API is optional. Generate a real feature when you are ready to persist domain data."
        />
      ) : (
        <ul className="ui-list">
          {items.map((item) => (
            <li key={item.id}>
              <ExampleCard example={item} />
            </li>
          ))}
        </ul>
      )}
    </main>
  );
}

// src/templates/frontend/angular/src/app/features/example/pages/examples.page.ts
import { Component, inject } from "@angular/core";
import { FormBuilder, ReactiveFormsModule, Validators } from "@angular/forms";
import { Store } from "@ngrx/store";
import { ExampleCardComponent } from "../components/example-card.component";
import { ExampleActions } from "../store/example.actions";
import {
  selectExampleError,
  selectExampleItems,
} from "../store/example.selectors";
import { PageHeaderComponent } from "../../../shared/components/page-header.component";
import { EmptyStateComponent } from "../../../shared/components/empty-state.component";
import { ErrorStateComponent } from "../../../shared/components/error-state.component";

@Component({
  selector: "app-examples-page",
  standalone: true,
  imports: [ReactiveFormsModule, ExampleCardComponent, PageHeaderComponent, EmptyStateComponent, ErrorStateComponent],
  template: `
    <div class="ui-page">
      <app-page-header
        title="Architecture sample"
        description="Page → NgRx → feature service → HttpClient. This slice exists so the generated client has a working module before you add domain features."
      >
        <button type="button" class="ui-btn ui-btn-ghost" (click)="load()">Load sample</button>
      </app-page-header>

      @if (error(); as message) {
        <app-error-state [description]="message" />
      }

      <form class="ui-card" style="margin: 1.2rem 0" [formGroup]="form" (ngSubmit)="create()">
        <h3>Create a sample record</h3>
        <label class="ui-field">
          Name
          <input class="ui-input" formControlName="name" />
        </label>
        <label class="ui-field">
          Description
          <textarea class="ui-input" rows="3" formControlName="description"></textarea>
        </label>
        <button type="submit" class="ui-btn ui-btn-primary">Save</button>
      </form>

      @if (items().length === 0) {
        <app-empty-state
          title="No sample records"
          description="The sample API is optional. Generate a real feature when you are ready to persist domain data."
        />
      } @else {
        <ul class="ui-list">
          @for (item of items(); track item.id) {
            <li>
              <app-example-card [example]="item" />
            </li>
          }
        </ul>
      }
    </div>
  `,
})
export class ExamplesPageComponent {
  private readonly store = inject(Store);
  private readonly formBuilder = inject(FormBuilder);

  readonly items = this.store.selectSignal(selectExampleItems);
  readonly error = this.store.selectSignal(selectExampleError);

  readonly form = this.formBuilder.nonNullable.group({
    name: ["", [Validators.required, Validators.maxLength(200)]],
    description: ["", [Validators.maxLength(2000)]],
  });

  load() {
    this.store.dispatch(ExampleActions.loadExamples({ query: { page: 1, pageSize: 10 } }));
  }

  create() {
    if (this.form.invalid) {
      this.form.markAllAsTouched();
      return;
    }

    this.store.dispatch(ExampleActions.createExample({ input: this.form.getRawValue() }));
  }
}
