// src/templates/frontend/angular/src/app/shared/components/confirm-dialog.component.ts
import { Component, input, output } from "@angular/core";

@Component({
  selector: "app-confirm-dialog",
  standalone: true,
  template: `
    @if (open()) {
      <div class="ui-dialog-backdrop" role="dialog" aria-modal="true" [attr.aria-labelledby]="titleId">
        <div class="ui-dialog">
          <h2 [id]="titleId">{{ title() }}</h2>
          <p>{{ message() }}</p>
          <div class="ui-dialog-actions">
            <button type="button" class="ui-btn ui-btn-ghost" (click)="cancel.emit()">
              {{ cancelLabel() }}
            </button>
            <button type="button" class="ui-btn ui-btn-danger" (click)="confirm.emit()">
              {{ confirmLabel() }}
            </button>
          </div>
        </div>
      </div>
    }
  `,
})
export class ConfirmDialogComponent {
  readonly titleId = "confirm-dialog-title";
  readonly open = input(false);
  readonly title = input.required<string>();
  readonly message = input.required<string>();
  readonly confirmLabel = input("Confirm");
  readonly cancelLabel = input("Cancel");
  readonly confirm = output<void>();
  readonly cancel = output<void>();
}

// src/templates/frontend/react/common/src/shared/components/ConfirmDialog.tsx
"use client";

import { useState, type ReactNode } from "react";

type ConfirmDialogProps = {
  open: boolean;
  title: string;
  message: string;
  confirmLabel?: string;
  cancelLabel?: string;
  onConfirm: () => void;
  onCancel: () => void;
};

export function ConfirmDialog({
  open,
  title,
  message,
  confirmLabel = "Confirm",
  cancelLabel = "Cancel",
  onConfirm,
  onCancel,
}: ConfirmDialogProps) {
  if (!open) {
    return null;
  }

  return (
    <div className="ui-dialog-backdrop" role="dialog" aria-modal="true" aria-labelledby="confirm-dialog-title">
      <div className="ui-dialog">
        <h2 id="confirm-dialog-title">{title}</h2>
        <p>{message}</p>
        <div className="ui-dialog-actions">
          <button type="button" className="ui-btn ui-btn-ghost" onClick={onCancel}>
            {cancelLabel}
          </button>
          <button type="button" className="ui-btn ui-btn-danger" onClick={onConfirm}>
            {confirmLabel}
          </button>
        </div>
      </div>
    </div>
  );
}

export function useConfirmDialog() {
  const [state, setState] = useState<{
    open: boolean;
    title: string;
    message: string;
    resolve: ((value: boolean) => void) | null;
  }>({
    open: false,
    title: "",
    message: "",
    resolve: null,
  });

  function confirm(title: string, message: string): Promise<boolean> {
    return new Promise((resolve) => {
      setState({ open: true, title, message, resolve });
    });
  }

  const dialog: ReactNode = (
    <ConfirmDialog
      open={state.open}
      title={state.title}
      message={state.message}
      onCancel={() => {
        state.resolve?.(false);
        setState((current) => ({ ...current, open: false, resolve: null }));
      }}
      onConfirm={() => {
        state.resolve?.(true);
        setState((current) => ({ ...current, open: false, resolve: null }));
      }}
    />
  );

  return { confirm, dialog };
}
