// src/templates/frontend/angular/src/app/layouts/auth-layout/auth-layout.component.ts
import { Component } from "@angular/core";
import { RouterLink, RouterOutlet } from "@angular/router";

@Component({
  selector: "app-auth-layout",
  standalone: true,
  imports: [RouterLink, RouterOutlet],
  template: `
    <div class="min-h-screen">
      <header class="border-b border-zinc-200 px-6 py-4">
        <a routerLink="/" class="text-sm underline">Back to site</a>
      </header>
      <router-outlet />
    </div>
  `,
})
export class AuthLayoutComponent {}

// src/templates/frontend/react/vite/src/app/layouts/AuthLayout.tsx
import { Link, Outlet } from "react-router-dom";

export function AuthLayout() {
  return (
    <div className="min-h-screen">
      <header className="border-b border-zinc-200 px-6 py-4">
        <Link className="text-sm underline" to="/">
          Back to site
        </Link>
      </header>
      <Outlet />
    </div>
  );
}
