// src/templates/frontend/angular/src/app/layouts/dashboard-layout/dashboard-layout.component.ts
import { Component } from "@angular/core";
import { RouterLink, RouterOutlet } from "@angular/router";
import { generatedDashboardNav } from "../../navigation/generated-dashboard-nav";

@Component({
  selector: "app-dashboard-layout",
  standalone: true,
  imports: [RouterLink, RouterOutlet],
  template: `
    <div class="min-h-screen">
      <header class="border-b border-zinc-200 px-6 py-4">
        <nav class="mx-auto flex max-w-5xl flex-wrap gap-4 text-sm">
          <a routerLink="/dashboard" class="underline">Dashboard</a>
          @for (item of navItems; track item.path) {
            <a [routerLink]="item.path" class="underline">{{ item.label }}</a>
          }
          <a routerLink="/" class="underline">Website</a>
        </nav>
      </header>
      <router-outlet />
    </div>
  `,
})
export class DashboardLayoutComponent {
  readonly navItems = generatedDashboardNav;
}

// src/templates/frontend/react/vite/src/app/layouts/DashboardLayout.tsx
import { Link, Outlet } from "react-router-dom";
import { generatedDashboardNav } from "@/navigation/generated-dashboard-nav";

export function DashboardLayout() {
  return (
    <div className="min-h-screen">
      <header className="border-b border-zinc-200 px-6 py-4">
        <nav className="mx-auto flex max-w-5xl flex-wrap gap-4 text-sm">
          <Link className="underline" to="/dashboard">
            Dashboard
          </Link>
          {generatedDashboardNav.map((item) => (
            <Link key={item.href} className="underline" to={item.href}>
              {item.label}
            </Link>
          ))}
          <Link className="underline" to="/">
            Website
          </Link>
        </nav>
      </header>
      <Outlet />
    </div>
  );
}
