// src/templates/frontend/angular/src/app/layouts/website-layout/website-layout.component.ts
import { Component } from "@angular/core";
import { RouterLink, RouterOutlet } from "@angular/router";

@Component({
  selector: "app-website-layout",
  standalone: true,
  imports: [RouterLink, RouterOutlet],
  template: `
    <div class="min-h-screen">
      <header class="border-b border-zinc-200 px-6 py-4">
        <nav class="mx-auto flex max-w-5xl gap-4 text-sm">
          <a routerLink="/" class="underline">Home</a>
          <a routerLink="/examples" class="underline">Examples</a>
          <a routerLink="/login" class="underline">Auth</a>
          <a routerLink="/dashboard" class="underline">Dashboard</a>
        </nav>
      </header>
      <router-outlet />
    </div>
  `,
})
export class WebsiteLayoutComponent {}

// src/templates/frontend/react/vite/src/app/layouts/WebsiteLayout.tsx
import { Link, Outlet } from "react-router-dom";

export function WebsiteLayout() {
  return (
    <div className="min-h-screen">
      <header className="border-b border-zinc-200 px-6 py-4">
        <nav className="mx-auto flex max-w-5xl gap-4 text-sm">
          <Link className="underline" to="/">
            Home
          </Link>
          <Link className="underline" to="/examples">
            Examples
          </Link>
          <Link className="underline" to="/login">
            Auth
          </Link>
          <Link className="underline" to="/dashboard">
            Dashboard
          </Link>
        </nav>
      </header>
      <Outlet />
    </div>
  );
}
