// src/templates/frontend/angular/src/app/features/auth/register.page.ts
import { Component } from "@angular/core";

@Component({
  selector: "app-register-page",
  standalone: true,
  template: `
    <main class="mx-auto flex min-h-screen max-w-md flex-col gap-4 px-6 py-16">
      <h1 class="text-2xl font-semibold">Register</h1>
      <p class="text-zinc-600">
        Account registration will be added in a later generator phase.
      </p>
    </main>
  `,
})
export class RegisterPageComponent {}

// src/templates/frontend/react/vite/src/app/pages/RegisterPage.tsx
export function RegisterPage() {
  return (
    <main className="mx-auto flex min-h-screen max-w-md flex-col gap-4 px-6 py-16">
      <h1 className="text-2xl font-semibold">Register</h1>
      <p className="text-zinc-600">
        Account registration will be added in a later generator phase.
      </p>
    </main>
  );
}
