// src/templates/frontend/angular/src/app/shared/components/loading-state.component.ts
import { Component, input } from "@angular/core";

@Component({
  selector: "app-loading-state",
  standalone: true,
  template: `
    <div class="ui-loading" role="status">
      <span class="ui-spinner" aria-hidden="true"></span>
      <h3>{{ title() }}</h3>
      @if (description()) {
        <p class="ui-note">{{ description() }}</p>
      }
    </div>
  `,
})
export class LoadingStateComponent {
  readonly title = input("Loading");
  readonly description = input<string>();
}

// src/templates/frontend/react/common/src/shared/components/loaders/LoadingState.tsx
type LoadingStateProps = {
  title?: string;
  description?: string;
};

export function LoadingState({
  title = "Loading",
  description = "Fetching the latest data…",
}: LoadingStateProps) {
  return (
    <div className="ui-loading" role="status" aria-live="polite">
      <span className="ui-spinner" aria-hidden="true" />
      <h3>{title}</h3>
      <p className="ui-note">{description}</p>
    </div>
  );
}
