// src/templates/frontend/react/common/src/shared/components/auth/AuthFrame.tsx
"use client";

import type { ReactNode } from "react";
import type { ReactElement } from "react";
import type { AppLinkProps } from "@/shared/navigation/app-link";

type AuthFrameProps = {
  productName: string;
  title: string;
  description: string;
  children: ReactNode;
  Link: (props: AppLinkProps) => ReactElement;
};

export function AuthFrame({
  productName,
  title,
  description,
  children,
  Link,
}: AuthFrameProps) {
  return (
    <div className="ui-auth">
      <aside className="ui-auth-aside">
        <Link href="/" className="ui-brand">
          <span className="ui-brand-mark" aria-hidden="true">
            <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
              <rect x="1" y="1" width="5" height="5" rx="1.2" fill="currentColor" />
              <rect x="8" y="8" width="5" height="5" rx="1.2" fill="currentColor" />
            </svg>
          </span>
          {productName}
        </Link>
        <div>
          <h2 style={{ margin: 0, fontSize: "1.8rem", letterSpacing: "-0.04em" }}>
            A quiet place to authenticate.
          </h2>
          <p>
            Sign-in lives outside the dashboard on purpose. Session handling stays isolated from the public site and workspace.
          </p>
        </div>
        <p style={{ margin: 0, fontSize: "0.85rem", color: "rgb(250 250 250 / 0.55)" }}>
          <Link href="/">
            Back to site
          </Link>
        </p>
      </aside>
      <section className="ui-auth-main">
        <div className="ui-auth-card">
          <h1>{title}</h1>
          <p>{description}</p>
          {children}
        </div>
      </section>
    </div>
  );
}

// src/templates/frontend/angular/src/app/shared/components/auth-frame.component.ts
import { Component, input } from "@angular/core";
import { RouterLink } from "@angular/router";

@Component({
  selector: "app-auth-frame",
  standalone: true,
  imports: [RouterLink],
  template: `
    <div class="ui-auth">
      <aside class="ui-auth-aside">
        <a routerLink="/" class="ui-brand" style="color: inherit">__DISPLAY_NAME__</a>
        <div>
          <h2 style="margin:0;font-size:1.8rem;letter-spacing:-0.04em">A quiet place to authenticate.</h2>
          <p>Sign-in lives outside the dashboard on purpose. Session handling stays isolated from the public site and workspace.</p>
        </div>
        <p style="margin:0;font-size:0.85rem;color:rgb(250 250 250 / 0.55)">
          <a routerLink="/" style="color:inherit">Back to site</a>
        </p>
      </aside>
      <section class="ui-auth-main">
        <div class="ui-auth-card">
          <h1>{{ title() }}</h1>
          <p>{{ description() }}</p>
          <ng-content />
        </div>
      </section>
    </div>
  `,
})
export class AuthFrameComponent {
  readonly title = input.required<string>();
  readonly description = input.required<string>();
}
