// src/templates/frontend/react/common/src/shared/components/empty-state/ErrorState.tsx
import type { ReactNode } from "react";
import { CircleAlert } from "lucide-react";

type ErrorStateProps = {
  title?: string;
  description: string;
  action?: ReactNode;
};

export function ErrorState({
  title = "Something went wrong",
  description,
  action,
}: ErrorStateProps) {
  return (
    <div className="ui-error" role="alert">
      <span className="ui-card-icon">
        <CircleAlert size={16} />
      </span>
      <h3>{title}</h3>
      <p className="ui-note">{description}</p>
      {action}
    </div>
  );
}

// src/templates/frontend/angular/src/app/shared/components/error-state.component.ts
import { Component, input } from "@angular/core";

@Component({
  selector: "app-error-state",
  standalone: true,
  template: `
    <div class="ui-error" role="alert">
      <span class="ui-card-icon" aria-hidden="true">
        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8">
          <circle cx="12" cy="12" r="9" />
          <path d="M12 8v5M12 16.5h.01" />
        </svg>
      </span>
      <h3>{{ title() }}</h3>
      <p class="ui-note">{{ description() }}</p>
      <ng-content />
    </div>
  `,
})
export class ErrorStateComponent {
  readonly title = input("Something went wrong");
  readonly description = input.required<string>();
}
