// src/templates/frontend/react/common/src/shared/components/cards/StatCard.tsx
import type { LucideIcon } from "lucide-react";

type StatCardProps = {
  label: string;
  value: string;
  hint?: string;
  icon?: LucideIcon;
};

export function StatCard({ label, value, hint, icon: Icon }: StatCardProps) {
  return (
    <article className="ui-card ui-stat">
      {Icon ? (
        <span className="ui-card-icon">
          <Icon size={16} />
        </span>
      ) : null}
      <span>{label}</span>
      <strong>{value}</strong>
      {hint ? <span>{hint}</span> : null}
    </article>
  );
}

// src/templates/frontend/angular/src/app/shared/components/stat-card.component.ts
import { Component, input } from "@angular/core";

@Component({
  selector: "app-stat-card",
  standalone: true,
  template: `
    <article class="ui-card ui-stat">
      <span>{{ label() }}</span>
      <strong>{{ value() }}</strong>
      @if (hint()) {
        <span>{{ hint() }}</span>
      }
    </article>
  `,
})
export class StatCardComponent {
  readonly label = input.required<string>();
  readonly value = input.required<string>();
  readonly hint = input<string>();
}
