// src/templates/frontend/react/common/src/modules/category/pages/CreateCategoryPage.tsx
"use client";

import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useCategoriesController } from "../hooks/useCategoriesController";
import {
  createCategorySchema,
  type CreateCategoryFormValues,
} from "../schemas/category.schema";
import { PageHeader } from "@/shared/components/common/PageHeader";
import { ErrorState } from "@/shared/components/empty-state/ErrorState";

export default function CreateCategoryPage() {
  const { status, error, create } = useCategoriesController();
  const form = useForm<CreateCategoryFormValues>({
    resolver: zodResolver(createCategorySchema),
    defaultValues: {
      name: "",
      description: "",
    },
  });

  return (
    <main className="ui-container ui-page" style={{ paddingTop: "2.5rem", paddingBottom: "3.5rem" }}>
      <PageHeader
        title="Create category"
        description="Add a category name and optional description."
        actions={
          <a href="/dashboard/category" className="ui-btn ui-btn-ghost">
            Back to list
          </a>
        }
      />

      {status === "failed" && error ? <ErrorState description={error} /> : null}

      <form
        className="ui-card"
        style={{ margin: "1.2rem 0" }}
        onSubmit={form.handleSubmit((values) => create(values))}
      >
        <label className="ui-field">
          Name
          <input className="ui-input" {...form.register("name")} />
        </label>
        <label className="ui-field">
          Description
          <textarea className="ui-input" rows={3} {...form.register("description")} />
        </label>
        <button type="submit" className="ui-btn ui-btn-primary" disabled={status === "loading"}>
          Save category
        </button>
      </form>
    </main>
  );
}

// src/templates/frontend/angular/src/app/features/category/pages/create-category.page.ts
import { Component, inject } from "@angular/core";
import { FormBuilder, ReactiveFormsModule, Validators } from "@angular/forms";
import { RouterLink } from "@angular/router";
import { Store } from "@ngrx/store";
import { CategoryActions } from "../store/category.actions";
import { selectCategoryError } from "../store/category.selectors";
import { PageHeaderComponent } from "../../../shared/components/page-header.component";
import { ErrorStateComponent } from "../../../shared/components/error-state.component";

@Component({
  selector: "app-create-category-page",
  standalone: true,
  imports: [ReactiveFormsModule, RouterLink, PageHeaderComponent, ErrorStateComponent],
  template: `
    <div class="ui-page">
      <app-page-header
        title="Create category"
        description="Add a category name and optional description."
      >
        <a routerLink="/dashboard/category" class="ui-btn ui-btn-ghost">Back to list</a>
      </app-page-header>

      @if (error(); as message) {
        <app-error-state [description]="message" />
      }

      <form class="ui-card" style="margin: 1.2rem 0" [formGroup]="form" (ngSubmit)="create()">
        <label class="ui-field">
          Name
          <input class="ui-input" formControlName="name" />
        </label>
        <label class="ui-field">
          Description
          <textarea class="ui-input" rows="3" formControlName="description"></textarea>
        </label>
        <button type="submit" class="ui-btn ui-btn-primary">Save category</button>
      </form>
    </div>
  `,
})
export class CreateCategoryPageComponent {
  private readonly store = inject(Store);
  private readonly formBuilder = inject(FormBuilder);

  readonly error = this.store.selectSignal(selectCategoryError);

  readonly form = this.formBuilder.nonNullable.group({
    name: ["", [Validators.required, Validators.maxLength(200)]],
    description: ["", [Validators.maxLength(2000)]],
  });

  create() {
    if (this.form.invalid) {
      this.form.markAllAsTouched();
      return;
    }

    this.store.dispatch(CategoryActions.createCategory({ input: this.form.getRawValue() }));
  }
}
