// src/templates/frontend/react/common/src/modules/example/components/ExampleCard.tsx
"use client";

import { motion } from "framer-motion";
import type { Example } from "../types/example.types";

export function ExampleCard({ example }: { example: Example }) {
  return (
    <motion.article
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      className="rounded-lg border border-zinc-200 p-4"
    >
      <h2 className="text-lg font-medium">{example.name}</h2>
      <p className="mt-2 text-sm text-zinc-600">{example.description}</p>
    </motion.article>
  );
}

// src/templates/frontend/angular/src/app/features/example/components/example-card.component.ts
import { Component, input } from "@angular/core";
import { Example } from "../models/example.model";

@Component({
  selector: "app-example-card",
  standalone: true,
  template: `
    <article class="rounded-lg border border-zinc-200 p-4">
      <h2 class="text-lg font-medium">{{ example().name }}</h2>
      <p class="mt-2 text-sm text-zinc-600">{{ example().description }}</p>
    </article>
  `,
})
export class ExampleCardComponent {
  readonly example = input.required<Example>();
}
